# Generated by Django 2.1.7 on 2019-06-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdatabase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='company',
            field=models.CharField(choices=[('Epam', 'Epam'), ('Global Logic', 'Global Logic'), ('Microsoft', 'Microsoft'), ('Google', 'Google'), ('Amazon', 'Amazon')], max_length=150),
        ),
    ]
