# Generated by Django 2.1.7 on 2019-06-08 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicationmodels', '0003_auto_20190608_1021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Стаття', 'verbose_name_plural': 'Статті'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Місце', 'verbose_name_plural': 'Місця'},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'verbose_name': 'Видання'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name': 'Ресторан', 'verbose_name_plural': 'Ресторани'},
        ),
        migrations.AlterModelOptions(
            name='waiter',
            options={'verbose_name': 'Офіціант', 'verbose_name_plural': 'Офіціанти'},
        ),
    ]
