# Generated by Django 2.1.7 on 2019-06-08 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicationmodels', '0004_auto_20190608_1026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'verbose_name': 'Видання', 'verbose_name_plural': 'Видання'},
        ),
    ]
