# Generated by Django 2.1.7 on 2019-06-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationmodels', '0006_auto_20190608_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='date',
            field=models.DateField(verbose_name='Дата народження'),
        ),
        migrations.AlterField(
            model_name='example',
            name='dateTime',
            field=models.DateTimeField(verbose_name='Початок роботи'),
        ),
        migrations.AlterField(
            model_name='example',
            name='dc',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Трудова оцінка'),
        ),
        migrations.AlterField(
            model_name='example',
            name='em',
            field=models.EmailField(max_length=254, verbose_name='Електрона адреса'),
        ),
        migrations.AlterField(
            model_name='example',
            name='txt',
            field=models.TextField(max_length=20, verbose_name='Про мене'),
        ),
    ]
