# Generated by Django 2.1.7 on 2019-06-10 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicationmodels', '0009_auto_20190608_1106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='example',
            options={'verbose_name': 'Співробітники', 'verbose_name_plural': 'Співробітники'},
        ),
    ]
